import type { AppData } from './types'
import { defaultAppearance } from './lib/appearance.ts'

/**
 * Entirely fictional first-run data. It gives a new user a coherent task,
 * person, source, itinerary, and map example without shipping personal data.
 */
export const seedData: AppData = {
  profile: {
    name: '访客',
  },
  places: [
    { id: 'home', name: '居所（示例）', category: 'home', lat: 31.2304, lng: 121.4737, note: '虚构示例坐标；请在地图中改成自己的常用区域。' },
    { id: 'library', name: '市图书馆（示例）', category: 'study', lat: 31.2114, lng: 121.4435, note: '用于演示见面任务和地点关联。' },
    { id: 'gym', name: '训练场（示例）', category: 'health', lat: 31.2248, lng: 121.5033, note: '用于演示健康类任务。' },
    { id: 'campus', name: '校园（示例）', category: 'study', lat: 31.2991, lng: 121.5006, note: '近似范围示例，不代表任何真实用户的学校。', precision: 'approximate', radiusMeters: 1_200 },
    { id: 'oldtown', name: '旧城街区（示例）', category: 'explore', lat: 31.2254, lng: 121.4924, note: '用于演示探索类地点。', precision: 'approximate', radiusMeters: 850 },
    { id: 'cafe', name: '风铃咖啡（虚构）', category: 'social', lat: 31.2186, lng: 121.4662, note: '完全虚构的见面地点名称。' },
  ],
  people: [
    {
      id: 'p-demo-classmate',
      name: '示例同学',
      facts: ['对方在示例对话中表示想去图书馆借一本设计书。', '对方确认周六下午两点见面，并提醒携带校园卡。'],
      preferences: ['对方曾在一次明确表达中对设计类书籍表现出兴趣。'],
      advice: ['见面前确认具体出口，并检查校园卡是否随身。'],
      sourceIds: ['i-demo-1', 'i-demo-3'],
      conversationIds: ['folder:私聊/示例同学'],
      firstObservedAt: '2026-08-16T18:30:00',
      lastObservedAt: '2026-08-16T18:36:00',
      portrait: '现有示例证据只确认了一次图书馆邀约和对设计书的兴趣，信息不足以判断稳定性格。',
      platforms: ['本地文件'],
      model: 'fictional-release-example',
      createdAt: '2026-07-30T00:00:00',
    },
  ],
  dismissedPersonConversationIds: [],
  peopleModelVersion: 5,
  quests: [
    {
      id: 'q-demo-campus',
      title: '整理新学期材料',
      description: '把报到、课程、缴费和住宿材料整理成一页清单，并标出尚未确认的项目。',
      status: 'active',
      locationId: 'campus',
      characterIds: [],
      dueAt: '2026-08-20T20:00',
      tags: [],
      source: '虚构校园平台示例',
      atlasCategory: 'campus',
      atlasOrder: 0,
    },
    {
      id: 'q-demo-library',
      title: '确认周六图书馆见面细节',
      description: '与示例同学确认具体地铁出口，并按约定在周六下午两点见面。',
      status: 'available',
      locationId: 'library',
      characterIds: ['p-demo-classmate'],
      startAt: '2026-08-22T14:00',
      sourceCapturedAt: '2026-08-16T18:36:00',
      source: '本地文件 · 虚构示例',
      sourceIds: ['i-demo-1', 'i-demo-2', 'i-demo-3'],
      sourcePlatforms: ['本地文件'],
      tags: [],
      guidance: ['出发前确认地铁站出口，并带上校园卡。'],
      atlasCategory: 'friends',
      atlasOrder: 0,
    },
    {
      id: 'q-demo-card',
      title: '准备校园卡和借阅清单',
      description: '检查校园卡，并把想借的书写成短清单。',
      status: 'locked',
      locationId: 'home',
      characterIds: ['p-demo-classmate'],
      dueAt: '2026-08-22T12:00',
      sourceCapturedAt: '2026-08-16T18:36:00',
      parentId: 'q-demo-library',
      source: '本地文件 · 虚构示例',
      sourceIds: ['i-demo-3'],
      sourcePlatforms: ['本地文件'],
      tags: [],
      atlasCategory: 'study',
      atlasOrder: 0,
    },
    {
      id: 'q-demo-long-event',
      title: '新学期适应期',
      description: '长期记录课程节奏、作息和社交变化，每月回顾一次。',
      status: 'available',
      locationId: 'campus',
      characterIds: [],
      startAt: '2026-09-01',
      dueAt: '2027-07-15',
      tags: [],
      source: '手动示例',
      kind: 'long-event',
      atlasCategory: 'campus',
      atlasOrder: 1,
    },
    {
      id: 'q-demo-training',
      title: '完成一次恢复训练',
      description: '完成低强度热身、基础力量和拉伸，以恢复节奏为目标。',
      status: 'available',
      locationId: 'gym',
      characterIds: [],
      dueAt: '2026-08-05T18:00',
      tags: [],
      source: '手动示例',
      atlasCategory: 'wellbeing',
      atlasOrder: 0,
    },
    {
      id: 'q-demo-walk',
      title: '探索一条没走过的街道',
      description: '散步一小时，只记录三件真正让自己停下来的事。',
      status: 'done',
      previousStatus: 'available',
      locationId: 'oldtown',
      characterIds: [],
      startAt: '2026-07-30T17:30',
      tags: [],
      source: '手动示例',
      atlasCategory: 'life',
      atlasOrder: 0,
    },
  ],
  intel: [
    {
      id: 'i-demo-1',
      title: '示例同学：周六下午要不要一起去市图书馆？',
      summary: '示例同学：周六下午要不要一起去市图书馆？我想借那本设计书。',
      content: '周六下午要不要一起去市图书馆？我想借那本设计书。',
      source: '本地文件',
      conversationId: 'folder:私聊/示例同学',
      conversationName: '示例同学',
      conversationKind: 'direct',
      speaker: '示例同学',
      messageType: 'text',
      speakerRole: 'other',
      capturedAt: '2026-08-16T18:30:00',
      status: 'reviewed',
    },
    {
      id: 'i-demo-2',
      title: '你：可以，我下午两点在地铁站出口见你。',
      summary: '你：可以，我下午两点在地铁站出口见你。',
      content: '可以，我下午两点在地铁站出口见你。',
      source: '本地文件',
      conversationId: 'folder:私聊/示例同学',
      conversationName: '示例同学',
      conversationKind: 'direct',
      speaker: '你',
      messageType: 'text',
      speakerRole: 'self',
      capturedAt: '2026-08-16T18:34:00',
      status: 'reviewed',
    },
    {
      id: 'i-demo-3',
      title: '示例同学：好，周六下午两点见。',
      summary: '示例同学：好，周六下午两点见。别忘了带校园卡。',
      content: '好，周六下午两点见。别忘了带校园卡。',
      source: '本地文件',
      conversationId: 'folder:私聊/示例同学',
      conversationName: '示例同学',
      conversationKind: 'direct',
      speaker: '示例同学',
      messageType: 'text',
      speakerRole: 'other',
      capturedAt: '2026-08-16T18:36:00',
      status: 'reviewed',
    },
  ],
  archive: { version: 1, messageCount: 3, conversationCount: 1, identifiedConversationCount: 1, directConversationCount: 1, groupConversationCount: 0, messagesWithoutConversation: 0 },
  aiCandidates: [],
  aiSettings: {
    mode: 'balanced',
    instructions: '只把明确可执行、对现实生活有帮助的事项整理成任务；不要臆测隐私或制造压力。',
    autoEnabled: false,
    intervalHours: 24,
    recencyPolicy: 'balanced',
    concurrency: 4,
    feedback: [],
    promptInstructions: {
      task: '优先保留仍需你处理、具体可执行的安排。约见、返校、报名、缴费、回复、预约和截止事项优先；闲聊、历史通知和已过期事项不输出。',
      people: '只提取对方自己明确说过的信息。优先保留能帮助你更好相处的明确边界、沟通方式、重复偏好和长期变化。单次表达只能写成“曾表示”或“有过单次评价”，不能升级为稳定习惯或性格。',
      peopleMerge: '把已核验事实整理成自然、有人味但克制的人物理解：优先写对方如何沟通、明确在意或拒绝什么、重复出现的偏好、互动方式和有证据的变化；不要写关系分数、心理诊断或武断性格标签。建议必须帮助你尊重对方选择、先确认再行动、留出拒绝空间，并且每条都能回到至少两条证据。信息不足的方面直接省略。',
      taskGuidance: '建议应具体、尊重边界，优先给出准备、确认、倾听和备选方案。涉及他人时先保护对方选择权，避免催促、试探和操控。信息不足时先建议补充时间、地点或对方当前偏好。',
    },
  },
  appearance: defaultAppearance,
  atlas: { categoryPositions: {} },
}

/** Return an isolated demo workspace for recovery and the reset action. */
export function createSeedData(): AppData {
  return structuredClone(seedData)
}
